Added RONEC dataset.
huggingface/datasets pull request #1493
Opened 2020-12-11 22:14 UTC by iliemihai

2020-12-11 22:40 UTC, rkc007 commented
Thanks for the PR @iliemihai . 

Few comments - 

Can you run - 
`python datasets-cli dummy_data ./datasets/ronec --auto_generate` to generate dummy data.

Also, before committing files run : 
`make style`
`flake8 datasets`
then you can add and commit files.

2020-12-11 23:03 UTC, iliemihai commented
> Thanks for the PR @iliemihai .
> 
> Few comments -
> 
> Can you run -
> `python datasets-cli dummy_data ./datasets/ronec --auto_generate` to generate dummy data.
> 
> Also, before committing files run :
> `make style`
> `flake8 datasets`
> then you can add and commit files.

Sorry, forgot to generate dummy data. I will do it now :D

2020-12-15 07:21 UTC, SBrandeis requested changes
Cool submission, thanks !

Can you please add the dataset card (README.md file) in the same directory as ronec.py ?
You will find a template file and a guide on how to complete it in the `templates` folder, at the root of the lib.
To quickly generate the YAML tags, you can run the [dataset-tagging](https://github.com/huggingface/datasets-tagging) app.

Feel free to reach out if you have questions !

2020-12-16 14:59 UTC, SBrandeis reviewed
Thanks for adding the dataset cards !
There are still a few missing fields that would be nice to have

2020-12-16 14:59 UTC, SBrandeis commented on datasets/ronec/README.md
> +[Needs More Information]
It would be nice to have an actual example here, in JSON format !

2020-12-16 14:59 UTC, SBrandeis commented on datasets/ronec/README.md
> +- entity-linking-retrieval
```suggestion
task_categories:
- structure-prediction
task_ids:
- named-entity-recognition
```

2020-12-16 14:59 UTC, SBrandeis commented on datasets/ronec/README.md
> +[Needs More Information]
```suggestion
@article{dumitrescu2019introducing,
  title={Introducing RONEC--the Romanian Named Entity Corpus},
  author={Dumitrescu, Stefan Daniel and Avram, Andrei-Marius},
  journal={arXiv preprint arXiv:1909.01247},
  year={2019}
}
```

2020-12-16 14:59 UTC, SBrandeis commented on datasets/ronec/README.md
> +Romanian
```suggestion
Romanian (`ro`)
```

2020-12-17 08:11 UTC, SBrandeis commented
Awesome, good job @iliemihai !
I think the PR is ready to merge.
@lhoestq would you mind double-checking this ?

2020-12-17 08:11 UTC, SBrandeis approved these changes

2020-12-17 14:20 UTC, lhoestq reviewed
Nice thank you for adding this one !

I just noticed that you removed the IOB markers in the labels, I think we should keep them.
You can get some inspiration from the [conll2003](https://github.com/huggingface/datasets/blob/master/datasets/conll2003/conll2003.py) script for example.

After changing the class labels you'll need to regenerate the dataset_infos.json file

2020-12-17 14:20 UTC, lhoestq commented on datasets/ronec/README.md
> +}
````suggestion
```
{'end': [19, 28, 42, 80], 
 'id': '1', 
 'ronec_class': [13, 4, 13, 8], 
 'sentence': ['Secretarul de stat al S.U.A., Colin Powell, începe un turneu în țările asiatice afectate de valurile seismice uriașe.'], 
 'start': [1, 22, 31, 72]
}
```
````

dict in markdown code block

2020-12-17 14:20 UTC, lhoestq commented on datasets/ronec/ronec.py
> +                        label = splits[10][2:]
Why do you remove the `B-`, `I-` and `O-` ?
We should keep them to follow the conll IOB format as in [conll2003](https://github.com/huggingface/datasets/blob/master/datasets/conll2003/conll2003.py#L168-L178) for example

2020-12-17 14:20 UTC, lhoestq commented on datasets/ronec/README.md
> +
could you add the full list of labels here ?

2020-12-17 14:20 UTC, lhoestq commented on datasets/ronec/README.md
> +- `end`: a `list` of `int32` features describing the start positions of each label in a sentence. Since a sentence can have more than one label, start will be a list with the starting offset of each
If we follow the conll2003 format we don't need those fields since each word will have one label

2020-12-17 14:20 UTC, lhoestq commented on datasets/ronec/README.md
> +- `sentence`: a `list` of `string` features.
to follow the conll2003 format can you rename it `tokens` instead of `sentence` ?

2020-12-21 14:08 UTC, lhoestq approved these changes
Nice thank you !

2020-12-21 14:37 UTC, lhoestq commented on datasets/ronec/ronec.py
> +    ]
```suggestion
    BUILDER_CONFIGS = [
        RONECConfig(name="ronec", version=VERSION, description="RONEC dataset"),
    ]
```
remove default config name

2020-12-21 14:39 UTC, lhoestq commented
Had to regenerate the dummy data since I just found out they were empty files

2020-12-21 14:48 UTC, merged