Speech commands
huggingface/datasets pull request #3335
Opened 2021-11-29 13:52 UTC by polinaeterna

## Attention: need help!
 
I'm confused with the correct train / val / test splits of both versions of this dataset. 

I found four sources of information about the dataset:

1. [TFDS card](https://www.tensorflow.org/datasets/catalog/speech_commands)
2. [paper](https://arxiv.org/pdf/1804.03209.pdf)
3. READMEs in archives with data. Archives can be downloaded via these links:
   - http://download.tensorflow.org/data/speech_commands_v0.01.tar.gz
   - http://download.tensorflow.org/data/speech_commands_test_set_v0.01.tar.gz
   - http://download.tensorflow.org/data/speech_commands_v0.02.tar.gz
   - http://download.tensorflow.org/data/speech_commands_test_set_v0.02.tar.gz

4. (not an original one but I considered this too) [SpeechCommands v0.01](https://github.com/huggingface/datasets/blob/master/datasets/superb/superb.py#L152) part from huggingface Superb dataset

## Version 0.01
I'm not sure if I picked the correct set of target words. TF script suggests that the command words are: 
['down', 'go', 'left', 'no', 'off', 'on', 'right', 'stop', 'up', 'yes']. See [this line](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/audio/speech_commands.py#L58). **Note that this script is actually for version two.** 
The same wordset is listed in SpeechCommands v0.01 in Superb. See [this line](https://github.com/huggingface/datasets/blob/master/datasets/superb/superb.py#L166). 
TFDS page also suggests that there are 12 classes in the dataset  (10 words, `_unknown_`, and `_silence_` aka `_background_noise_`).
**But** the paper states that the first version has twenty target words:

_This led me to pick twenty common words as the core of our vocabulary.  These included the digits zero to nine, and in version one, ten words that would be useful as commands in IoT or robotics applications;  "Yes", "No", "Up", "Down", "Left", "Right", "On", "Off", "Stop", and "Go"._  
(see Section 5.2 Word Choice of the paper, on the top of the page 4).

And if you examine the http://download.tensorflow.org/data/speech_commands_v0.01.tar.gz archive you'll see that there are folders for all these twenty words (as well as for some auxiliary words). 
The same is stated in this archive's README:

_Twenty core command words were recorded, with most speakers saying each of them five times. The core words are "Yes", "No", "Up", "Down", "Left", "Right", "On", "Off", "Stop", "Go", "Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", and "Nine". To help distinguish unrecognized words, there are also ten auxiliary words, which most speakers only said once. These include "Bed", "Bird", "Cat", "Dog", "Happy", "House", "Marvin", "Sheila",
"Tree", and "Wow"._

Also, the author provides a separate archive for the test set (http://download.tensorflow.org/data/speech_commands_test_set_v0.01.tar.gz)/ But if we examine this archive we'll see that it contains ten folders corresponding to target words, and audio files of other ten words that were targets in the major archive are contained in the `_unknown_` folder. The process of generating this test set archive is described in the paper,  see Section 7.1 Top-One Error, on the top of the page 7:

_The standard chosen for the TensorFlow speech commands example  code is to look for the ten words "Yes", "No", "Up", "Down", "Left", "Right", "On", "Off", "Stop", and "Go", and have one additional special label for “Unknown Word”, and another for “Silence” (no speech detected). The testing is then done by providing equal numbers of examples for each of the twelve categories, which means each class accounts for approximately 8.3% of the total. The "Unknown Word" category contains words randomly sampled from classes that are part of the target set. The "Silence" category has one-second clips extracted randomly from the background noise audio files._

**Is it really supposed to be like that? That the training and validation sets contain targets that in test set fall to another category (`_unknown_`). Or did I get something wrong?**

Personally, I decided to include all twenty words as labels, but this way ten of them belong to
`_unknown_` category in test set (since it is generated from the separate test archive,
similarly to the way it is done in TSDF and Superb scripts).

## Version 0.02

I encounter the same problem with the second version. Paper states that this version has four additional command words. See, again, Section 5.2 Word Choice of the paper (on the top of the page 4):

_In version 2 of the dataset, I added four more command words; “Backward”,  “Forward”, “Follow”, and “Learn”._

But, as I said, TF script, which is supposed to be for version 0.02, [provides only ten words](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/audio/speech_commands.py#L58). 

Also, in test set archive (http://download.tensorflow.org/data/speech_commands_test_set_v0.02.tar.gz) these four words again fall into `_unknown_` category.

## Summary

What's the best way to solve this:

- [ ] use only ten words as core words ("Yes", "No", "Up", "Down", "Left", "Right", "On", "Off", "Stop", and "Go") for both versions and preserve test sets as they are now

- [ ] preserve the core words as they are now: 20 words in version 0.01 ("Yes", "No", "Up", "Down", "Left", "Right", "On", "Off", "Stop", and "Go" + digits) and 24 words in version 0.02 (the same as in 0.01 + “Backward”, “Forward”, “Follow”, and “Learn”) **and** rewrite test set generation so that these words do not fall into the `_unknown_` category but are left as core classes.

2021-11-29 13:53 UTC, polinaeterna commented
OMG I hope it's more or less clear what I mean...

2021-11-29 17:25 UTC, polinaeterna commented
Closes  #3283

2021-11-29 17:40 UTC, polinaeterna commented
@anton-l ping

2021-11-29 18:46 UTC, anton-l requested changes
Thanks for working on this dataset, Polina! Feel free to convert this PR to review-ready once you add the auxiliary label field, the integration looks clean overall :slightly_smiling_face:

2021-11-29 18:46 UTC, anton-l commented on datasets/speech_commands/speech_commands.py
> +            version=datasets.Version("0.0.1"),
I think it's rather "0.1.0"?

2021-11-29 18:46 UTC, anton-l commented on datasets/speech_commands/speech_commands.py
> +            version=datasets.Version("0.0.2"),
Same here

2021-11-29 18:46 UTC, anton-l commented on datasets/speech_commands/speech_commands.py
> +                Contains more command and auxiliary words than version 0.01.
```suggestion
                Version 0.02 of the SpeechCommands dataset.
                Contains more commands and auxiliary words than version 0.01.
```

2021-11-29 18:46 UTC, anton-l commented on datasets/speech_commands/speech_commands.py
> +                # TODO: or maybe should I preserve words outside the WORDS list too and
Having the `full_label` field to keep the original words would be ideal, yes!

2021-11-29 18:46 UTC, anton-l commented on datasets/speech_commands/speech_commands.py
> +a mathematical simulations of noise.
```suggestion
There is also a `_background_noise_` class containing a set of longer audio clips that are either recordings or
a mathematical simulation of noise.
```

2021-11-29 18:46 UTC, anton-l commented on datasets/speech_commands/speech_commands.py
> +# Copyright 2020 The HuggingFace Datasets Authors and the current dataset script contributor.
```suggestion
# Copyright 2021 The HuggingFace Datasets Authors and the current dataset script contributor.
```

2021-11-29 18:46 UTC, anton-l commented on datasets/speech_commands/README.md
> +### Data Instances
Thanks for including the examples for different groups of lables!

2021-11-29 18:46 UTC, anton-l commented on datasets/speech_commands/README.md
> +- unknown
```suggestion
  v0.01:
    - 10K<n<100K
  v0.02:
    - 100K<n<1M
```

2021-11-29 18:46 UTC, anton-l commented on datasets/speech_commands/README.md
> +- keyword-spotting
```suggestion
- other-other-keyword-spotting
```

2021-12-01 14:34 UTC, polinaeterna commented
@lhoestq 
Hi Quentin! Thank you for your feedback and suggestions! 🤗

Yes, that was actually what I wanted to do next - I mean the steaming stuff :)
Also, I need to make some changes to the readme (to account for the updated features set).

Hopefully, I will be done by tomorrow afternoon if that's ok.

2021-12-04 10:19 UTC, polinaeterna commented
@lhoestq  Hi Quentin!

I've implemented (hopefully, correctly) the streaming compatibility but the problem with the current approach is that we first need to iterate over the full archive anyway to get the list of filenames for train and validation sets (see [this](https://github.com/huggingface/datasets/pull/3335/files#diff-aeea540d136025e30a842856779e9c6485a5dc6fc9eb7fd6d3be2acd2f49b8e3R186), the same approach is implemented in TFDS version). Only after that, we can generate examples, so we cannot stream the dataset before the first iteration ends and it takes some time. It's probably not the most effective way. 

If the streaming mode is turned off, this approach (with two iterations) is actually slower than the previous implementation (with archive extraction). 

My suggestion is to host separate archives for each split prepared in advance. That way there would be no need for iterating over the common archive to collect train and validation filenames.  @anton-l  suggested to make AWS mirrors for them. I've prepared these archives, for now you can take a look at them [here](https://drive.google.com/drive/u/0/folders/1oMrZHzPgHAKprKJuvih91CM8KMSzh_pL). I simplified their structure a bit so if we switch to using them, the code then should be changed (and simplified) a bit too.

2021-12-06 16:54 UTC, lhoestq commented
Hi ! Thanks for the changes :)

> My suggestion is to host separate archives for each split prepared in advance. That way there would be no need for iterating over the common archive to collect train and validation filenames. @anton-l suggested to make AWS mirrors for them. I've prepared these archives, for now you can take a look at them here. I simplified their structure a bit so if we switch to using them, the code then should be changed (and simplified) a bit too.

I agree, I just uploaded them on AWS

https://s3.amazonaws.com/datasets.huggingface.co/SpeechCommands/v0.01/v0.01_test.tar.gz
https://s3.amazonaws.com/datasets.huggingface.co/SpeechCommands/v0.01/v0.01_train.tar.gz
https://s3.amazonaws.com/datasets.huggingface.co/SpeechCommands/v0.01/v0.01_validation.tar.gz
https://s3.amazonaws.com/datasets.huggingface.co/SpeechCommands/v0.02/v0.02_test.tar.gz
https://s3.amazonaws.com/datasets.huggingface.co/SpeechCommands/v0.02/v0.02_validation.tar.gz

Note that in the future we can move those files to actual repositories on the Hugging Face Hub, since we are migrating the datasets from this repository to the Hugging Face Hub (as mirrors), to make them more accessible to the community.

2021-12-06 21:02 UTC, polinaeterna commented
@lhoestq Thank you! Gonna look at this tomorrow :)

2021-12-07 14:17 UTC, polinaeterna commented
@lhoestq I've modified the code to fit new data format, now it works for v0.01 but doesn't work for v0.02 as the training archive is missing. Could you please create a mirror for that one too? You can find it [here](https://drive.google.com/file/d/1mPjnVMYb-VhPprGlOX8v9TBT1GT-rtcp/view?usp=sharing)

And when it's done I'll need to regenerate all the meta / dummy stuff, and this version will be ready for a review :)

2021-12-09 11:15 UTC, lhoestq commented
Here you go :)
https://s3.amazonaws.com/datasets.huggingface.co/SpeechCommands/v0.02/v0.02_train.tar.gz

2021-12-09 17:38 UTC, lhoestq commented
FYI I juste merged a fix for the Windows CI error on `master`, feel free to merge `master` again into your branch

2021-12-09 18:07 UTC, lhoestq commented
All green ! I had to fix some minor stuff in the CI but it's good now

Next step is to mark it as ready for review, and I think it's all good so we can merge 🚀

2021-12-09 18:09 UTC, polinaeterna commented
@lhoestq 🤗

2021-12-09 18:57 UTC, anton-l approved these changes
Everything looks great now, will use it in the classification examples very soon! :slightly_smiling_face:

2021-12-10 10:29 UTC, lhoestq approved these changes
Awesome thank you :)

2021-12-10 10:30 UTC, merged

2021-12-10 10:31 UTC, LysandreJik commented
:tada: