Adding mMARCO dataset
huggingface/datasets pull request #3421
Opened 2021-12-13 00:56 UTC by lhbonifacio

Adding mMARCO (v1.1) to HF datasets.

2021-12-13 05:44 UTC, albertvillanova requested changes
Thanks @lhbonifacio for adding this dataset.

It is missing the dataset card, with all relevant information and metadata about the dataset. You can find:
- a template: https://github.com/huggingface/datasets/blob/master/templates/README.md
-  instructions to fill it:
  - https://github.com/huggingface/datasets/blob/master/ADD_NEW_DATASET.md#tag-the-dataset-and-write-the-dataset-card
  - https://github.com/huggingface/datasets/blob/master/templates/README_guide.md
-  and a complete example: https://github.com/huggingface/datasets/tree/master/datasets/eli5

2021-12-13 05:44 UTC, albertvillanova commented on datasets/mmarco/mmarco.py
> +        super(MsMarcoConfig, self).__init__(**kwargs)
No need to create a specific `datasets.BuilderConfig` subclass if you are not creating additional config attributes, others than name, description, version,...

2021-12-13 05:44 UTC, albertvillanova commented on datasets/mmarco/mmarco.py
> +        )
You can use `datasets.BuilderConfig` instead of custom `MsMarcoConfig`.

2021-12-20 18:13 UTC, hugoabonizio commented
Hi @albertvillanova we've made a major overhaul of the loading script including all configurations we're making available. Could you please review it again?

2022-01-03 11:23 UTC, hugoabonizio commented
@albertvillanova :ping_pong:

2022-01-12 03:59 UTC, catqaq commented
Hi there, i got an error about mmarco:
ConnectionError: Couldn't reach 'unicamp-dl/mmarco' on the Hub (ConnectionError)
code:
`from datasets import list_datasets, load_dataset
dataset = load_dataset('unicamp-dl/mmarco', language='portuguese')`

Any help will be appreciated!

2022-01-12 13:07 UTC, hugoabonizio commented
Hi @catqaq, we updated the loading script. Now you can load the datasets with:

```python
dataset = load_dataset('unicamp-dl/mmarco', 'portuguese')
```

You can check the list of supported languages and usage examples in [this link](https://huggingface.co/datasets/unicamp-dl/mmarco). Feel free to contact us if you have any issues.

2022-01-13 02:59 UTC, catqaq commented
> 



> Hi @catqaq, we updated the loading script. Now you can load the datasets with:
> 
> ```python
> dataset = load_dataset('unicamp-dl/mmarco', 'portuguese')
> ```
> 
> You can check the list of supported languages and usage examples in [this link](https://huggingface.co/datasets/unicamp-dl/mmarco). Feel free to contact us if you have any issues.

Thanks for your quick updates. So, how can i get the fixed version, install from the source?

2022-01-13 10:06 UTC, hugoabonizio commented
@catqaq you can load mMARCO using the namespace `unicamp-dl/mmarco` while this PR remains under review.

2022-09-30 13:52 UTC, albertvillanova commented
Thanks for your contribution, @lhbonifacio and  @hugoabonizio. And sorry for the late response.

We are removing the dataset scripts from this GitHub repo and moving them to the Hugging Face Hub: https://huggingface.co/datasets

As you already created this dataset under your organization namespace (https://huggingface.co/datasets/unicamp-dl/mmarco), I think we can safely close this PR.

We would suggest you complete your dataset card with the YAML tags, to make it searchable and discoverable.

Please, feel free to tell us if you need some help.

2022-10-03 09:37 UTC, closed without merging