Use `iter_files` instead of `str(Path(...)` in image dataset
huggingface/datasets pull request #3477
Opened 2021-12-23 16:26 UTC by mariosasko

Use `iter_files` in the `beans` and the `cats_vs_dogs` dataset scripts as suggested by @albertvillanova.

Additional changes:
* Fix `iter_files` in `MockDownloadManager` (see this [CI error](https://app.circleci.com/pipelines/github/huggingface/datasets/9247/workflows/2657ff8a-b531-4fd9-a9fc-6541a72e8d83/jobs/57028))
* Add support for `os.path.isdir` and `os.path.isfile` in streaming (`os.path.isfile` is needed in `StreamingDownloadManager`'s `iter_files` to make cats_vs_dogs streamable)

TODO:
- [ ] add tests for `xisdir` and `xisfile`

2021-12-24 07:50 UTC, albertvillanova requested changes
Thanks for all the enhancements, @mariosasko.

As discussed, the workaround in `iter_files` was temporal (it was valid only in some limited uses cases) and eventually would need fixing. In that moment I prioritized having a limited-working implementation rather than a general one. 

To have a generally valid implementation, first some fixing is needed in the custom FileSystems we have at `datasets`. I could have a look at that in another PR, so that you could merge it into this once that is fixed.

On the meantime, I have suggested some fixing to your implementation below.

2021-12-24 07:50 UTC, albertvillanova commented on src/datasets/utils/streaming_download_manager.py
> +        return fs.isfile(path)
```suggestion
        return fs.isfile(main_hop)
```

2021-12-24 07:50 UTC, albertvillanova commented on src/datasets/utils/streaming_download_manager.py
> +        return fs.isdir(path)
```suggestion
        return fs.isdir(main_hop)
```

2021-12-24 10:48 UTC, albertvillanova requested changes
This PR requires first being merged:
- #3481

2021-12-24 12:10 UTC, albertvillanova approved these changes
The failing test has nothing to do with this PR.

2021-12-27 16:07 UTC, lhoestq commented
`iter_archive` is about to support ZIP archives. I think we should use this no ?

2021-12-27 16:27 UTC, lhoestq commented
I'm not a big fan of having two functions that do the same thing. What do you think ?

2021-12-27 16:30 UTC, albertvillanova commented
They do not do the same thing:
- One iterates over files in a directory
- The other I guess will iterate over the members of an archive

2021-12-27 16:53 UTC, lhoestq commented
Makes sense ! Sounds good then - sorry for my misunderstanding

Note that `iter_archive` will be more performant for data streaming that `iter_files` thanks to the buffering so maybe in the future we can `iter_archive` for some of these datasets

2021-12-28 10:43 UTC, albertvillanova commented
Yes, @lhoestq I agree with you: once `iter_archive` supports zip files, it will be more suitable than `iter_files` for these 2 datasets.

Anyway, this PR also implements `isfile`/`isdir` in streaming mode, besides fixing `iter_files`. And I'm interested in having those in master.

Maybe, could we merge this PR into master and take note to refactor the datasets to use `iter_archive` once zip is supported?
Other option could be to split this PR into 2...

2021-12-28 14:09 UTC, lhoestq reviewed
Sure, let me add some tests for xisdir and xisfile and we can merge

2021-12-28 14:09 UTC, lhoestq commented on src/datasets/streaming.py
> +    patch_submodule(module, "os.path.isfile", wrap_auth(xisdir)).start()
```suggestion
    patch_submodule(module, "os.path.isdir", wrap_auth(xisdir)).start()
```

2021-12-28 15:14 UTC, lhoestq approved these changes
Alright let's merge this now :)

2021-12-28 15:15 UTC, merged