Multi-GPU support for `FaissIndex`
huggingface/datasets pull request #3721
Opened 2022-02-14 17:26 UTC by rentruewang

Per #3716 , current implementation does not take into consideration that `faiss` can run on multiple GPUs.

In this commit, I provided multi-GPU support for `FaissIndex` by modifying the device management in `IndexableMixin.add_faiss_index` and `FaissIndex.load`.

Now users are able to pass in
1. a positive integer (as usual) to use 1 GPU
2. a negative integer `-1` to use all GPUs
3. a list of integers e.g. `[0, 1]` to run only on those GPUs
4. Of course, passing in nothing still runs on CPU.

This closes: #3716

2022-02-15 08:01 UTC, rentruewang commented
Any love guys?

2022-02-15 10:10 UTC, albertvillanova requested changes
Thank you. Great job. Just a few comments/questions below...

2022-02-15 10:38 UTC, rentruewang commented on src/datasets/search.py
> +
Oh yeah, sorry I missed it. Thanks!

2022-02-15 10:53 UTC, rentruewang commented on src/datasets/search.py
> +        if self.device is not None:
Fixed in the latest commit

2022-02-15 10:54 UTC, rentruewang commented on src/datasets/search.py
> +        wrapper = cls(device=device)
Fixed in the latest commit.

2022-02-18 05:36 UTC, rentruewang commented
@albertvillanova Hi, is there anything else you want to add to this PR?

2022-02-18 19:13 UTC, lhoestq approved these changes
It looks all good for me thanks ! @albertvillanova do you want to do a final review ?

Maybe we can wait for https://github.com/huggingface/datasets/pull/3690 to be merged first, since it changes the documentation format - or we would en up with many conflicts

2022-02-18 19:41 UTC, rentruewang commented on src/datasets/search.py
> +                + "Please pass in either nothing, a positive int, a negative int, or a list of positive ints."
@lhoestq Thanks for the feedback! I am a big fan of f-strings as well. I was just concerned about support for `python3.5`, is that not currently supported?

2022-02-23 07:33 UTC, rentruewang commented
@albertvillanova Is there anything else you want me to add / modify?

2022-02-24 08:57 UTC, albertvillanova approved these changes
@rentruewang thank you again for your work!

I think this is OK.

Just, as @lhoestq suggested, maybe we should wait for other PR to be merged before this one, so that we avoid conflicts with the docstrings:
- #3690

2022-03-07 10:20 UTC, lhoestq commented
Hi @rentruewang , we updated the documentation on `master`, could you merge `master` into your branch please ?

2022-03-07 16:18 UTC, rentruewang commented
@lhoestq I've merge `huggingface/datasets/master` into this PR. Please review. Thanks! 🤗

2022-03-07 16:28 UTC, merged