Fix Audion.encode_example() in writing an array
huggingface/datasets pull request #3998
Opened 2022-03-23 20:32 UTC by polinaeterna

Closes  #3996

2022-03-23 20:41 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_3998). All of your documentation changes will be reflected on that endpoint.

2022-03-24 07:00 UTC, albertvillanova requested changes
Thanks a lot for the fix!

Do you think we could add some regression test on this issue?

2022-03-24 13:28 UTC, lhoestq approved these changes
Thanks ! and thanks for the test as well :)

2022-03-29 13:21 UTC, albertvillanova approved these changes
Great. Thank you!! :)

2022-03-29 14:16 UTC, merged