Add Accuracy Metric Card
huggingface/datasets pull request #4223
Opened 2022-04-26 15:10 UTC by emibaylor

- adds accuracy metric card
- updates docstring in accuracy.py
- adds .json file with metric card and docstring information

2022-04-26 15:22 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_4223). All of your documentation changes will be reflected on that endpoint.

2022-04-27 16:42 UTC, sashavor requested changes
A few minor issues (mostly adding some examples), otherwise this is great!

2022-04-27 16:42 UTC, sashavor commented on metrics/accuracy/README.md
> +```python
Why is there a second empty code snippet?

2022-05-03 12:48 UTC, sashavor approved these changes

2022-05-03 13:43 UTC, lhoestq commented on metrics/accuracy/accuracy.py
> +        {'accuracy': 0.3}
```suggestion
        {'accuracy': 3.0}
```

2022-05-03 13:50 UTC, lhoestq approved these changes
I did a small change to fix the doctest with `normalize=False`, it should fix the CI.

I added some suggestions to keep the right format to the docstrings as well.

When the CI is green and the docstrings have the right format feel free to merge :)

2022-05-03 13:50 UTC, lhoestq commented on metrics/accuracy/accuracy.py
> +- **accuracy** (`float` or `int`): Accuracy score. Minimum possible value is 0. Maximum possible value is 1.0, or the number of examples input, if `normalize` is set to `True`.. A higher score means
```suggestion
    accuracy (`float` or `int`): Accuracy score. Minimum possible value is 0. Maximum possible value is 1.0, or the number of examples input, if `normalize` is set to `True`.. A higher score means higher accuracy.
```

2022-05-03 14:20 UTC, merged