Add pearsonr mc, update functionality to match the original docs
huggingface/datasets pull request #4226
Opened 2022-04-26 18:30 UTC by emibaylor

- adds pearsonr metric card
- adds ability to return p-value
    - p-value was mentioned in the original docs as a return value, but there was no option to return it. I updated the _compute function slightly to have an option to return the p-value.

2022-04-26 18:39 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_4226). All of your documentation changes will be reflected on that endpoint.

2022-04-27 16:37 UTC, sashavor requested changes
A few minor comments, otherwise LGTM!

2022-04-27 16:37 UTC, sashavor commented on metrics/pearsonr/README.md
> +The Pearson correlation coefficient measures the linear relationship between two datasets. The calculation of the p-value relies on the assumption that each dataset is normally distributed. Like othe
I would put this part in the ### Output values section:

> Like other correlation coefficients, this one varies between -1 and +1 with 0 implying no correlation. Correlations of -1 or +1 imply an exact linear relationship. Positive correlations imply that as x increases, so does y. Negative correlations imply that as x increases, y decreases.

2022-04-27 16:37 UTC, sashavor commented on metrics/pearsonr/README.md
> +
I would suggest the following:

"As stated above, the calculation of the p-value relies on the assumption that each data set is normally distributed. This is not always the case, so verifying the true distribution of datasets is recommended."

2022-05-03 14:15 UTC, sashavor approved these changes

2022-05-03 16:41 UTC, lhoestq approved these changes
Thanks :) as before, I just added suggestions for the docstrings formats:

2022-05-03 16:41 UTC, lhoestq commented on metrics/pearsonr/pearsonr.py
> +- **return_pvalue** (`boolean`): If `True`, returns the p-value, along with the correlation coefficient. If `False`, returns only the correlation coefficient. Defaults to `False`.
```suggestion
    predictions (`list` of `int`): Predicted class labels, as returned by a model.
    references (`list` of `int`): Ground truth labels.
    return_pvalue (`boolean`): If `True`, returns the p-value, along with the correlation coefficient. If `False`, returns only the correlation coefficient. Defaults to `False`.
```

2022-05-03 16:41 UTC, lhoestq commented on metrics/pearsonr/pearsonr.py
> +- **p-value** (`float`): P-value, which roughly indicates the probability of an The p-value roughly indicates the probability of an uncorrelated system producing datasets that have a Pearson correlat
```suggestion
    pearsonr (`float`): Pearson correlation coefficient. Minimum possible value is -1. Maximum possible value is 1. Values of 1 and -1 indicate exact linear positive and negative relationships, respectively. A value of 0 implies no correlation.
    p-value (`float`): P-value, which roughly indicates the probability of an The p-value roughly indicates the probability of an uncorrelated system producing datasets that have a Pearson correlation at least as extreme as the one computed from these datasets. Minimum possible value is 0. Maximum possible value is 1. Higher values indicate higher probabilities.
```

2022-05-03 16:42 UTC, sashavor commented
thank you @lhoestq!! :hugs:

2022-05-03 17:02 UTC, merged