Update README.md
huggingface/datasets pull request #4290
Opened 2022-05-06 08:52 UTC by monk1337

Updating readme in medmcqa dataset.

2022-05-06 09:04 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_4290). All of your documentation changes will be reflected on that endpoint.

2022-05-22 15:04 UTC, monk1337 commented
@albertvillanova  Kindly check :)

2022-09-23 11:43 UTC, albertvillanova requested changes
Thanks for the update.

2022-09-23 11:43 UTC, albertvillanova commented on datasets/medmcqa/README.md
> +- **Paper:** https://proceedings.mlr.press/v174/pal22a/pal22a.pdf
We usually link to the abstract page (not the PDF):
```suggestion
- **Paper:** [MedMCQA: A Large-scale Multi-Subject Multi-Choice Dataset for Medical domain Question Answering](https://proceedings.mlr.press/v174/pal22a)
```

2022-09-30 11:49 UTC, albertvillanova approved these changes

2022-09-30 11:49 UTC, merged