add new dataset lccc
huggingface/datasets pull request #4416
Opened 2022-05-29 12:27 UTC by silverriver

Hi, I am trying to add a new dataset lccc.
All tests are passed.

2022-05-30 05:38 UTC, albertvillanova requested changes
Thanks @silverriver for adding this dataset!

The CI tests are still red: some comment below to fix them. Also, some additional comments so that the dataset card (README file) is more accurate.

2022-05-30 05:38 UTC, albertvillanova commented on datasets/lccc/README.md
> +- lccc
Tjhe value of `pretty_name` should be a string scalar, not a sequence:
```suggestion
pretty_name: LCCC
```

2022-05-30 05:38 UTC, albertvillanova commented on datasets/lccc/README.md
> +    - [Citation Information](#citation-information)
Missing section:
```suggestion
    - [Citation Information](#citation-information)
    - [Contributions](#contributions)
```

2022-05-30 05:38 UTC, albertvillanova commented on datasets/lccc/README.md
> +- **Homepage:** https://github.com/thu-coai/CDial-GPT
Homepage here should only be given if different from the GitHub repository:
```suggestion
```

2022-05-30 05:38 UTC, albertvillanova commented on datasets/lccc/README.md
> +["火锅 我 在 重庆 成都 吃 了 七八 顿 火锅", "哈哈哈哈 ！ 那 我 的 嘴巴 可能 要 烂掉 ！", "不会 的 就是 好 油腻"]
I think each data instance has a "dialog" key:
```suggestion
{
    "dialog": ["火锅 我 在 重庆 成都 吃 了 七八 顿 火锅", "哈哈哈哈 ！ 那 我 的 嘴巴 可能 要 烂掉 ！", "不会 的 就是 好 油腻"]
}
```
Please put this example between triple backticks.

2022-05-30 05:38 UTC, albertvillanova commented on datasets/lccc/README.md
> +however, we are providing LCCC in jsonl format here.
This section is about the data fields in the generated dataset, not the original source. Maybe something like:

```suggestion
- `dialog` (list of strings): List of utterances consisting of a dialogue.
```

2022-05-30 05:38 UTC, albertvillanova commented on datasets/lccc/README.md
> +|:---:|:---:|:---:|
Better aligned to the right:
```suggestion
|---:|---:|---:|
```

2022-05-30 05:38 UTC, albertvillanova commented on datasets/lccc/README.md
> +[Needs More Information]
Missing information: please add the citation between triple backticks
```suggestion
@inproceedings{wang2020chinese,
  title={A Large-Scale Chinese Short-Text Conversation Dataset},
  author={Wang, Yida and Ke, Pei and Zheng, Yinhe and Huang, Kaili and Jiang, Yong and Zhu, Xiaoyan and Huang, Minlie},
  booktitle={NLPCC},
  year={2020},
  url={https://arxiv.org/abs/2008.03946}
}

### Contributions

Thanks to [@github-username](https://github.com/<github-username>) for adding this dataset.
```
Also please fill the Contributions section with your GitHub username.

2022-05-30 14:01 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_4416). All of your documentation changes will be reflected on that endpoint.

2022-05-30 14:05 UTC, albertvillanova commented on datasets/lccc/lccc.py
> +                        "split": "train",
I just realized `split` is not used in `_generate_examples`: therefore, there is no need to pass it. See suggested changes below.
```suggestion
```

2022-05-30 14:05 UTC, albertvillanova commented on datasets/lccc/lccc.py
> +                    gen_kwargs={"filepath": os.path.join(downloaded_data["test"]), "split": "test"},
```suggestion
                    gen_kwargs={"filepath": os.path.join(downloaded_data["test"])},
```

2022-05-30 14:06 UTC, albertvillanova commented on datasets/lccc/lccc.py
> +                        "split": "dev",
```suggestion
```

2022-05-30 14:06 UTC, albertvillanova commented on datasets/lccc/lccc.py
> +    def _generate_examples(self, filepath, split):
```suggestion
    def _generate_examples(self, filepath):
```

2022-05-31 01:15 UTC, silverriver commented
Thank you very much for your help @albertvillanova .

I think have fixed all your comment

2022-05-31 07:22 UTC, silverriver commented on datasets/lccc/README.md
> +}
Done

2022-06-02 09:13 UTC, merged

2022-06-14 17:41 UTC, lhoestq commented
Hi ! The dataset seems to be a duplicate of https://huggingface.co/datasets/silver/lccc - next time no need to add it on github if it's already available on huggingface.co ;)

2022-06-15 03:27 UTC, silverriver commented
> Hi ! The dataset seems to be a duplicate of https://huggingface.co/datasets/silver/lccc - next time no need to add it on github if it's already available on huggingface.co ;)

OK, sorry for the inconvenience. I have closed another two PRs since these datasets are already available on huggingface.co

2022-06-15 10:28 UTC, lhoestq commented
It's fine, thanks @silverriver for adding these datasets !