hellaswag: add non-empty description to fix metadata issue
huggingface/datasets pull request #4810
Opened 2022-08-09 10:21 UTC by julien-c

2022-08-09 10:29 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_4810). All of your documentation changes will be reflected on that endpoint.

2022-08-09 11:11 UTC, albertvillanova requested changes
Thanks for the fix, @julien-c.

Once the description has been updated in the script, the metadata JSON file should be regenerated as well:
```
{"default": {"description": "\n", ...
```
by using the CLI:
```
datasets-cli test datasets/hellaswag --save_infos --all_configs
```

Moreover, once this dataset is modified, our CI requires additional quality fixes in its documentation card:
```
E           The following issues were found for the README at `/home/runner/work/datasets/datasets/datasets/hellaswag/README.md`:
E           -	Expected some content in section `Dataset Summary` but it is empty.
E           -	Expected some text in section `Dataset Summary` but it is empty (text in subsections are ignored).

E           The following issues have been found in the dataset cards:
E           YAML tags:
E           __init__() missing 8 required positional arguments: 'annotations_creators', 'language_creators', 'license', 'multilinguality', 'size_categories', 'source_datasets', 'task_categories', and 'task_ids'

2022-08-11 14:11 UTC, julien-c commented
Are the `metadata JSON file` not on their way to deprecation? 😆😇

IMO, more generally than this particular PR, the contribution process should be simplified now that many validation checks happen on the hub side.

Keeping this open in the meantime to get more potential feedback!

2022-09-23 11:33 UTC, albertvillanova approved these changes
Thanks for the fix.

We are merging the dataset fixes before removing the scripts from GitHub.

2022-09-23 11:33 UTC, merged