fix billsum license and data source field
huggingface/datasets pull request #4851
Opened 2022-08-15 14:37 UTC by kashif

Fixed the data source and license fields

2022-08-15 14:45 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_4851). All of your documentation changes will be reflected on that endpoint.

2022-08-22 10:16 UTC, albertvillanova requested changes
Thanks for this additional information.

Just a minor fix (see below).

2022-08-22 10:16 UTC, albertvillanova commented on datasets/billsum/README.md
>  [More Information Needed](https://github.com/huggingface/datasets/blob/master/CONTRIBUTING.md#how-to-contribute-to-the-dataset-cards)
This information should be placed under the subsection "Initial Data Collection and Normalization":
```suggestion
#### Initial Data Collection and Normalization

The data consists of three parts: US training bills, US test bills and California test bills. The US bills were collected from the [Govinfo](https://github.com/unitedstates/congress) service provided by the United States Government Publishing Office (GPO) under CC0-1.0 license. The California, bills from the 2015-2016 session were are from the legislature’s [website](https://leginfo.legislature.ca.gov/).
```

2022-08-22 12:25 UTC, kashif commented
thanks @albertvillanova done thank you!

2022-08-22 13:40 UTC, merged