Finish Deprecating the `fs=` arg
huggingface/datasets pull request #5393
Opened 2022-12-28 15:33 UTC by dconathan

See #5385 for some discussion on this

The `fs=` arg was depcrecated from `Dataset.save_to_disk` and `Dataset.load_from_disk` in `2.8.0` (to be removed in `3.0.0`).  There are a few other places where the `fs=` arg was still used (functions/methods in `datasets.info` and `datasets.load`).  This PR adds a similar behavior, warnings and the `storage_options=` arg to these functions and methods.

One question: should the "deprecated" / "added" versions be `2.8.1` for the docs/warnings on these?  Right now I'm going with "fs was deprecated in 2.8.0" but "storage_options= was added in 2.8.1" where appropriate.

@mariosasko

2022-12-29 06:51 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_5393). All of your documentation changes will be reflected on that endpoint.

2022-12-29 07:02 UTC, albertvillanova requested changes
Thanks for the deprecation. Some minor suggested fixes below...

Also note that the corresponding tests should be updated as well.

2022-12-29 07:02 UTC, albertvillanova commented on src/datasets/info.py
> +                "'fs' was is deprecated in favor of 'storage_options' in version 2.8.0 and will be removed in 3.0.0.\n"
```suggestion
                "'fs' was deprecated in favor of 'storage_options' in version 2.9.0 and will be removed in 3.0.0.\n"
```

2022-12-29 07:02 UTC, albertvillanova commented on src/datasets/load.py
> +            <Deprecated version="2.8.0">
```suggestion
            <Deprecated version="2.9.0">
```

2022-12-29 07:02 UTC, albertvillanova commented on src/datasets/load.py
> +            `fs` was deprecated in version 2.8.0 and will be removed in 3.0.0.
```suggestion
            `fs` was deprecated in version 2.9.0 and will be removed in 3.0.0.
```

2022-12-29 07:02 UTC, albertvillanova commented on src/datasets/load.py
> +            Please use `storage_options` instead, e.g. `storage_options=fs.storage_options`
```suggestion
            Please use `storage_options` instead, e.g. `storage_options=fs.storage_options`.
```

2022-12-29 07:02 UTC, albertvillanova commented on src/datasets/load.py
> +            <Added version="2.8.1"/>
```suggestion
            <Added version="2.9.0"/>
```

2022-12-29 07:02 UTC, albertvillanova commented on src/datasets/load.py
> +            "'fs' was is deprecated in favor of 'storage_options' in version 2.8.0 and will be removed in 3.0.0.\n"
```suggestion
            "'fs' was deprecated in favor of 'storage_options' in version 2.9.0 and will be removed in 3.0.0.\n"
```

2022-12-29 14:13 UTC, dconathan commented
> Thanks for the deprecation. Some minor suggested fixes below...
> 
> Also note that the corresponding tests should be updated as well.

Thanks for the suggestions/typo fixes.  I updated the failing test - passing locally now

2023-01-05 15:44 UTC, lhoestq commented
Nice thanks !

I believe you also need to update `_load_info` and `_save_info` in `builder.py` - they're still passing `fs=self._fs` instead of `storage_options=self._fs.storage_options`

This should remove the remaining warnings in the CI such as 

```python
tests/test_builder.py::test_builder_with_filesystem_download_and_prepare_reload
tests/test_load.py::test_load_dataset_local[False]
tests/test_load.py::test_load_dataset_local[True]
tests/test_load.py::test_load_dataset_zip_csv[csv_path-False]
tests/test_load.py::test_load_dataset_then_move_then_reload
  /opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datasets/info.py:344: FutureWarning: 'fs' was deprecated in favor of 'storage_options' in version 2.9.0 and will be removed in 3.0.0.
  You can remove this warning by passing 'storage_options=fs.storage_options' instead.
```

2023-01-10 16:06 UTC, albertvillanova requested changes
Thanks again for all the work, @dconathan.

I agree with @lhoestq that we should better address all remaining `fs` deprecation warnings with this PR.

For example, there are still some deprecation warnings when calling `Dataset.load_from_disk` with `fs`. See: https://github.com/huggingface/datasets/blob/232a43943e87dfedcc328a9a3d3b4d89ea5c6627/src/datasets/load.py#L1819

or `DatasetDict.load_from_disk` with `fs`. See: https://github.com/huggingface/datasets/blob/232a43943e87dfedcc328a9a3d3b4d89ea5c6627/src/datasets/load.py#L1821

These docstrings should also be updated: 
https://github.com/huggingface/datasets/blob/232a43943e87dfedcc328a9a3d3b4d89ea5c6627/src/datasets/filesystems/s3filesystem.py#L98
https://github.com/huggingface/datasets/blob/232a43943e87dfedcc328a9a3d3b4d89ea5c6627/src/datasets/filesystems/s3filesystem.py#L111

2023-01-14 20:37 UTC, dconathan commented
re: docstring, I assume passing in `storage_options=s3.storage_options` is correct/necessary to pass the secrets?

2023-01-14 21:05 UTC, dconathan commented
what about 
https://github.com/huggingface/datasets/blob/5b793dd8c43bf6e85f165238becb3c64f6cd3ed0/src/datasets/filesystems/__init__.py#L43-L54

2023-01-18 11:02 UTC, albertvillanova approved these changes
Thanks again for all your work on this PR, @dconathan.

I think the function `is_remote_filesystem` should be kept as it is.

We are going to re-run the CI. Once all green, we can merge.

2023-01-18 12:35 UTC, merged