Allow loading/saving of FAISS index using fsspec
huggingface/datasets pull request #5526
Opened 2023-02-10 23:37 UTC by Dref360

Fixes #5428

Allow loading/saving of FAISS index using fsspec:
1. Simply use BufferedIOWriter/Reader to Read/Write indices on fsspec stream.
2. Needed `mockfs` in the test, so I took it out of the `TestCase`. Let me know if that makes sense.

2023-02-10 23:41 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_5526). All of your documentation changes will be reflected on that endpoint.

2023-02-13 19:42 UTC, alvarobartt reviewed
Just checked this and left some comments, hope you don't mind... Good work 💪🏻

2023-02-13 19:42 UTC, alvarobartt commented on src/datasets/search.py
> +            index = faiss.write_index(index, faiss.BufferedIOWriter(faiss.PyCallbackIOWriter(f.write)))
There's no need to capture `index` here, right?

```suggestion
            faiss.write_index(index, faiss.BufferedIOWriter(faiss.PyCallbackIOWriter(f.write)))
```

2023-02-13 19:42 UTC, alvarobartt commented on tests/test_search.py
> +def test_serialization(mockfs):
IMO the function above should be kept to still run the test to make sure that local storage works, while you can rename this to something like:

```suggestion
def test_serialization_fs(mockfs):
```

To be compliant with other functions like e.g. https://github.com/huggingface/datasets/blob/cc637d107ef3e3b9948691379312a8099b6476aa/tests/test_arrow_dataset.py#L3655

2023-02-13 21:08 UTC, Dref360 commented
Thanks for the quick review! I updated the code with your suggestion

2023-02-14 12:53 UTC, albertvillanova requested changes
Thanks for the enhancement, @Dref360.

2023-02-14 12:53 UTC, albertvillanova commented on src/datasets/search.py
> +            file (`str`): The path to the serialized faiss index on disk or remote URI (e.g. `"s3//my-bucket/index.faiss"`).
Typo:
```suggestion
            file (`str`): The path to the serialized faiss index on disk or remote URI (e.g. `"s3://my-bucket/index.faiss"`).
```

2023-02-14 12:53 UTC, albertvillanova commented on src/datasets/search.py
> +            file (`str`): The path to the serialized faiss index on disk or remote URI (e.g. `"s3//my-bucket/index.faiss"`).
As above:
```suggestion
            file (`str`): The path to the serialized faiss index on disk or remote URI (e.g. `"s3://my-bucket/index.faiss"`).
```

2023-02-14 12:53 UTC, albertvillanova commented on src/datasets/search.py
> +                Key/value pairs to be passed on to the file-system backend, if any.
Version added...
```suggestion
                Key/value pairs to be passed on to the file-system backend, if any.
                
                <Added version="2.10.0"/>
                
```

2023-02-14 12:53 UTC, albertvillanova commented on src/datasets/search.py
> +                Key/value pairs to be passed on to the file-system backend, if any.
```suggestion
                Key/value pairs to be passed on to the file-system backend, if any.
                
                <Added version="2.10.0"/>
```

2023-02-22 16:37 UTC, Dref360 commented
Thanks for the quick review @albertvillanova! I updated the code with your suggestions

2023-02-24 15:44 UTC, mariosasko reviewed
Thanks, one nit from me. Other than that, looks all good!

2023-02-24 15:44 UTC, mariosasko commented on src/datasets/search.py
> +                <Added version="2.10.0"/>
```suggestion
                <Added version="2.11.0"/>
```

2023-03-22 16:17 UTC, mariosasko approved these changes
Thanks! @albertvillanova Your requested changes are addressed now, so I think we can merge. Do you agree?

2023-03-27 14:49 UTC, albertvillanova approved these changes
Thanks!!

2023-03-27 15:18 UTC, merged