Better error message when combining dataset dicts instead of datasets
huggingface/datasets pull request #5861
Opened 2023-05-15 10:36 UTC by lhoestq

close https://github.com/huggingface/datasets/issues/5851

2023-05-15 10:40 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_5861). All of your documentation changes will be reflected on that endpoint.

2023-05-16 16:24 UTC, mariosasko approved these changes
LGTM!

We could use this for-loop to check if all input datasets share the same type (`Dataset`/`Iterable`), but maybe the current solution is easier to read.

2023-05-17 06:38 UTC, albertvillanova requested changes
Thanks for the fix.

I find the validations in both methods quite convoluted:
- first (in the loop you have implemented) we iterate over all `datasets` to check if an element is instance of `DatasetDict` or `IterableDatasetDict`
- second we take the first element of `datasets` (`datasets[0]`) to check if it is not an instance of `Dataset` or `IterableDataset`
- third we iterate over the rest of element of `datasets` (`datasets[[1:]]`) to check if they are an instance of the same type as the first element

Maybe we could really simplify the validation by just checking if the elements in the list of `datasets` are:
- either all an instance of `Dataset` 
- or all an instance of `IterableDataset`

and raise a ValueError otherwise

2023-05-17 06:38 UTC, albertvillanova commented on src/datasets/combine.py
> +            if not datasets[i]:
Nit: better use `dataset` than `datasets[i]`. The same in all cases below.

2023-05-17 11:58 UTC, lhoestq commented
Having those different checks helps providing an appropriate error message.

If the input is a dict, we suggest to select a split. If the input lists is a mix of iterable and non-iterable, we mention that it must be one or the other.

2023-05-17 12:42 UTC, albertvillanova reviewed
Do we really need to iterate over all datasets 2 times to validate them?

Feel free to merge as it is...

2023-05-23 10:32 UTC, merged