Fix regex `get_data_files` formatting for url base paths
huggingface/datasets pull request #6322
Opened 2023-10-19 19:45 UTC by ZachNagengast

With this pr https://github.com/huggingface/datasets/pull/6309, it is formatting the entire base path into regex, which results in the undesired formatting error `doesn't match the pattern` because of the line in `glob_patter_to_regex`: `.replace("//", "/")`:
- Input: `hf://datasets...`
- Output: `hf:/datasets/...`

This fix will only convert the `split_pattern` to regex and keep the `base_path` unchanged.

cc @albertvillanova hopefully this still works with your implementation

2023-10-20 10:02 UTC, albertvillanova requested changes
Thanks for the proposed fix, @ZachNagengast.

The reason why I used the the `glob_pattern_to_regex` in the entire `pattern` is because otherwise I got an error for Windows local paths: a `base_path` like `'C:\\Users\\runneradmin...` makes the function `string_to_dict` raise `re.error: incomplete escape \U at position 2`

See: https://github.com/huggingface/datasets/actions/runs/6544904352/job/17772361643

We should include a test that includes the case you mention, and find a solution that works for all cases.

2023-10-20 10:10 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_6322). All of your documentation changes will be reflected on that endpoint.

2023-10-20 18:25 UTC, ZachNagengast commented
> The reason why I used the the glob_pattern_to_regex in the entire pattern is because otherwise I got an error for Windows local paths: a base_path like 'C:\\Users\\runneradmin... made the function string_to_dict raise re.error: incomplete escape \U at position 2

What is the expected inputs and outputs for the windows `base_path`

2023-10-23 13:57 UTC, lhoestq commented
We took the liberty of continuing this PR to include it it today's patch release :)
I hope you don't mind

2023-10-23 14:26 UTC, lhoestq commented on src/datasets/data_files.py
> +            }
This is for old `push_to_hub` to work: they push custom splits using this pattern in the `data` directory.
New `push_to_hub` have some YAML to specify the pattern to use, so `get_data_patterns` isn't called

2023-10-23 14:29 UTC, albertvillanova commented on src/datasets/data_files.py
> +            }
OK, all clear now. Thanks.

2023-10-23 14:29 UTC, albertvillanova approved these changes

2023-10-23 14:31 UTC, merged