Remove deprecated code
huggingface/datasets pull request #6761
Opened 2024-03-28 09:57 UTC by Wauplin

What does this PR do?
1. remove `list_files_info` in favor of `list_repo_tree`. As of `0.23`, `list_files_info` will be removed for good. `datasets` had a utility to support both pre-0.20 and post-0.20 versions. Since `hfh` version is already pinned to `>=0.21.2`, I removed the legacy part.
2. `preupload_lfs_files` had also a different behavior between `<0.20` and `>=0.20`. I remove it since huggingface_hub is now pinned to `>=0.21.2`
3. `hf_hub_url` is overwritten to default to the dataset repo_type. I do think it is misleading to keep the same method naming for it. I renamed it to `get_dataset_url` for clarity. Let me know if you prefer to see this change reverted.

2024-03-28 10:02 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_6761). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-03-28 10:30 UTC, lhoestq commented
Thanks for cleaning this :) I'm also fine with renaming `hf_dataset_url` (and not `get_dataset_url` as you said in your OP)

2024-03-29 07:29 UTC, albertvillanova requested changes
Great! Thank you. We forgot to remove all this dead code.

There are however some red CI tests to be fixed...

2024-03-29 12:12 UTC, Wauplin commented
@albertvillanova Sorry about that, tests are now fixed! :)

2024-03-29 13:08 UTC, albertvillanova approved these changes
Great! Thanks again.

2024-03-29 13:18 UTC, merged